// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joykmvfqogxvokvynahj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveWttdmZxb2d4dm9rdnluYWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjMyMTcsImV4cCI6MjA2MDQzOTIxN30.JRpYXX-5-Ffa40raWcnwDgF0z3AzszIL1rfuQScxwGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);